# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 450)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.accountBox = QtWidgets.QGroupBox(self.centralwidget)
        self.accountBox.setGeometry(QtCore.QRect(50, 40, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accountBox.setFont(font)
        self.accountBox.setObjectName("accountBox")
        self.emailEdit = QtWidgets.QLineEdit(self.accountBox)
        self.emailEdit.setGeometry(QtCore.QRect(80, 32, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.emailEdit.setFont(font)
        self.emailEdit.setObjectName("emailEdit")
        self.emailText = QtWidgets.QLabel(self.accountBox)
        self.emailText.setGeometry(QtCore.QRect(10, 30, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.emailText.setFont(font)
        self.emailText.setObjectName("emailText")
        self.passwordText = QtWidgets.QLabel(self.accountBox)
        self.passwordText.setGeometry(QtCore.QRect(10, 58, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordText.setFont(font)
        self.passwordText.setObjectName("passwordText")
        self.passwordEdit = QtWidgets.QLineEdit(self.accountBox)
        self.passwordEdit.setGeometry(QtCore.QRect(80, 60, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setObjectName("passwordEdit")
        self.downloadTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.downloadTabWidget.setGeometry(QtCore.QRect(40, 200, 521, 131))
        self.downloadTabWidget.setObjectName("downloadTabWidget")
        self.DownloadAll = QtWidgets.QWidget()
        self.DownloadAll.setObjectName("DownloadAll")
        self.parseLinkButton = QtWidgets.QCommandLinkButton(self.DownloadAll)
        self.parseLinkButton.setGeometry(QtCore.QRect(30, 10, 191, 31))
        self.parseLinkButton.setObjectName("parseLinkButton")
        self.parseDownloadLinkButton = QtWidgets.QCommandLinkButton(self.DownloadAll)
        self.parseDownloadLinkButton.setGeometry(QtCore.QRect(290, 10, 191, 31))
        self.parseDownloadLinkButton.setObjectName("parseDownloadLinkButton")
        self.downloadFinishLinkButton = QtWidgets.QCommandLinkButton(self.DownloadAll)
        self.downloadFinishLinkButton.setGeometry(QtCore.QRect(30, 50, 191, 31))
        self.downloadFinishLinkButton.setObjectName("downloadFinishLinkButton")
        self.downloadTabWidget.addTab(self.DownloadAll, "")
        self.oneLessonDownload = QtWidgets.QWidget()
        self.oneLessonDownload.setObjectName("oneLessonDownload")
        self.lessonLinkEdit = QtWidgets.QLineEdit(self.oneLessonDownload)
        self.lessonLinkEdit.setGeometry(QtCore.QRect(150, 10, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lessonLinkEdit.setFont(font)
        self.lessonLinkEdit.setText("")
        self.lessonLinkEdit.setObjectName("lessonLinkEdit")
        self.lessonLinkText = QtWidgets.QLabel(self.oneLessonDownload)
        self.lessonLinkText.setGeometry(QtCore.QRect(20, 10, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lessonLinkText.setFont(font)
        self.lessonLinkText.setObjectName("lessonLinkText")
        self.downloadCurseButton = QtWidgets.QPushButton(self.oneLessonDownload)
        self.downloadCurseButton.setGeometry(QtCore.QRect(180, 40, 111, 33))
        self.downloadCurseButton.setObjectName("downloadCurseButton")
        self.downloadTabWidget.addTab(self.oneLessonDownload, "")
        self.directoryText = QtWidgets.QLabel(self.centralwidget)
        self.directoryText.setGeometry(QtCore.QRect(60, 150, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.directoryText.setFont(font)
        self.directoryText.setObjectName("directoryText")
        self.directoryBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.directoryBrowse.setGeometry(QtCore.QRect(470, 150, 71, 21))
        self.directoryBrowse.setObjectName("directoryBrowse")
        self.directoryPath = QtWidgets.QLineEdit(self.centralwidget)
        self.directoryPath.setGeometry(QtCore.QRect(230, 150, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.directoryPath.setFont(font)
        self.directoryPath.setText("")
        self.directoryPath.setObjectName("directoryPath")
        self.removeDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeDataButton.setGeometry(QtCore.QRect(350, 350, 191, 33))
        self.removeDataButton.setObjectName("removeDataButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.downloadTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DownloadGB"))
        self.accountBox.setTitle(_translate("MainWindow", "GeekBrains account"))
        self.emailText.setText(_translate("MainWindow", "E-mail:"))
        self.passwordText.setText(_translate("MainWindow", "Пароль:"))
        self.parseLinkButton.setText(_translate("MainWindow", "Пропарсить"))
        self.parseDownloadLinkButton.setText(_translate("MainWindow", "Пропарсить и скачать"))
        self.downloadFinishLinkButton.setText(_translate("MainWindow", "Скачать"))
        self.downloadTabWidget.setTabText(self.downloadTabWidget.indexOf(self.DownloadAll), _translate("MainWindow", "Скачать все"))
        self.lessonLinkText.setText(_translate("MainWindow", "Ссылка на урок:"))
        self.downloadCurseButton.setText(_translate("MainWindow", "Скачать урок"))
        self.downloadTabWidget.setTabText(self.downloadTabWidget.indexOf(self.oneLessonDownload), _translate("MainWindow", "Скачать один урок"))
        self.directoryText.setText(_translate("MainWindow", "Рабочая директория:"))
        self.directoryBrowse.setText(_translate("MainWindow", "Обзор"))
        self.removeDataButton.setText(_translate("MainWindow", "Очистить все данные из базы"))

