MAIN_LINK = 'https://geekbrains.ru/'
COURSES_LINK_PREFIX = 'education/'
WEBINAR_TYPE_PREFIX = 'lessons/'
VIDEO_TYPE_PREFIX = 'chapters/'
INTERACTIVE_TYPE_PREFIX = 'study_groups/'
WEBINAR_HOMEWORK_PREFIX = 'homework/'
INTERACTIVE_HOMEWORK_PREFIX = 'homeworks/'
